package cn.learn.mapp;

// Generated 2015-5-14 10:00:42 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * WdWordSentence generated by hbm2java
 */
public class WdWordSentence implements java.io.Serializable {

	private Integer id;
	private Integer wordId;
	private Integer defId;
	private String defName;
	private String sentence;
	private String sentenceCn;
	private Date createTime;
	private Date updateTime;

	public WdWordSentence() {
	}

	public WdWordSentence(Integer wordId, Integer defId, String defName,
			String sentence, String sentenceCn, Date createTime, Date updateTime) {
		this.wordId = wordId;
		this.defId = defId;
		this.defName = defName;
		this.sentence = sentence;
		this.sentenceCn = sentenceCn;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getWordId() {
		return this.wordId;
	}

	public void setWordId(Integer wordId) {
		this.wordId = wordId;
	}

	public Integer getDefId() {
		return this.defId;
	}

	public void setDefId(Integer defId) {
		this.defId = defId;
	}

	public String getDefName() {
		return this.defName;
	}

	public void setDefName(String defName) {
		this.defName = defName;
	}

	public String getSentence() {
		return this.sentence;
	}

	public void setSentence(String sentence) {
		this.sentence = sentence;
	}

	public String getSentenceCn() {
		return this.sentenceCn;
	}

	public void setSentenceCn(String sentenceCn) {
		this.sentenceCn = sentenceCn;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
