package cn.learn.mapp;

// Generated 2015-5-14 10:00:42 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * WdWordTest generated by hbm2java
 */
public class WdWordTest implements java.io.Serializable {

	private Integer id;
	private String testName;
	private Integer testBookId;
	private String testBook;
	private String teacherCode;
	private String teacherName;
	private Date endTime;
	private Date createTime;
	private Date updateTime;

	public WdWordTest() {
	}

	public WdWordTest(String testName, Integer testBookId, String testBook,
			String teacherCode, String teacherName, Date endTime,
			Date createTime, Date updateTime) {
		this.testName = testName;
		this.testBookId = testBookId;
		this.testBook = testBook;
		this.teacherCode = teacherCode;
		this.teacherName = teacherName;
		this.endTime = endTime;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTestName() {
		return this.testName;
	}

	public void setTestName(String testName) {
		this.testName = testName;
	}

	public Integer getTestBookId() {
		return this.testBookId;
	}

	public void setTestBookId(Integer testBookId) {
		this.testBookId = testBookId;
	}

	public String getTestBook() {
		return this.testBook;
	}

	public void setTestBook(String testBook) {
		this.testBook = testBook;
	}

	public String getTeacherCode() {
		return this.teacherCode;
	}

	public void setTeacherCode(String teacherCode) {
		this.teacherCode = teacherCode;
	}

	public String getTeacherName() {
		return this.teacherName;
	}

	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
