package cn.learn.mapp;

// Generated 2015-5-14 10:00:42 by Hibernate Tools 3.4.0.CR1

/**
 * Words generated by hbm2java
 */
public class Words implements java.io.Serializable {

	private Integer id;
	private String word;
	private String meaning;
	private String root;
	private String rootMeaning;
	private Integer handoutPage;
	private String pronuncation;
	private String maleVoive;

	public Words() {
	}

	public Words(String word, String meaning, String root, String rootMeaning,
			Integer handoutPage, String pronuncation, String maleVoive) {
		this.word = word;
		this.meaning = meaning;
		this.root = root;
		this.rootMeaning = rootMeaning;
		this.handoutPage = handoutPage;
		this.pronuncation = pronuncation;
		this.maleVoive = maleVoive;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getWord() {
		return this.word;
	}

	public void setWord(String word) {
		this.word = word;
	}

	public String getMeaning() {
		return this.meaning;
	}

	public void setMeaning(String meaning) {
		this.meaning = meaning;
	}

	public String getRoot() {
		return this.root;
	}

	public void setRoot(String root) {
		this.root = root;
	}

	public String getRootMeaning() {
		return this.rootMeaning;
	}

	public void setRootMeaning(String rootMeaning) {
		this.rootMeaning = rootMeaning;
	}

	public Integer getHandoutPage() {
		return this.handoutPage;
	}

	public void setHandoutPage(Integer handoutPage) {
		this.handoutPage = handoutPage;
	}

	public String getPronuncation() {
		return this.pronuncation;
	}

	public void setPronuncation(String pronuncation) {
		this.pronuncation = pronuncation;
	}

	public String getMaleVoive() {
		return this.maleVoive;
	}

	public void setMaleVoive(String maleVoive) {
		this.maleVoive = maleVoive;
	}

}
