package cn.xdf.learn.entity;

// Generated 2015-5-14 10:00:42 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * WdWord generated by hbm2java
 */
public class WdWord implements java.io.Serializable {

	private Integer id;
	private String word;
	private String phoneticUs;
	private String pronunUsMan;
	private Integer serverId;
	private Integer wordRootId;
	private Integer bookId;
	private Integer characterId;
	private Integer pageNo;
	private String remarks;
	private Integer createBy;
	private Date createDate;
	private Integer updateBy;
	private Date updateDate;
	private Integer delFlag;

	public WdWord() {
	}

	public WdWord(String word, String phoneticUs, String pronunUsMan,
			Integer serverId, Integer wordRootId, Integer bookId,
			Integer characterId, Integer pageNo, String remarks,
			Integer createBy, Date createDate, Integer updateBy,
			Date updateDate, Integer delFlag) {
		this.word = word;
		this.phoneticUs = phoneticUs;
		this.pronunUsMan = pronunUsMan;
		this.serverId = serverId;
		this.wordRootId = wordRootId;
		this.bookId = bookId;
		this.characterId = characterId;
		this.pageNo = pageNo;
		this.remarks = remarks;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
		this.delFlag = delFlag;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getWord() {
		return this.word;
	}

	public void setWord(String word) {
		this.word = word;
	}

	public String getPhoneticUs() {
		return this.phoneticUs;
	}

	public void setPhoneticUs(String phoneticUs) {
		this.phoneticUs = phoneticUs;
	}

	public String getPronunUsMan() {
		return this.pronunUsMan;
	}

	public void setPronunUsMan(String pronunUsMan) {
		this.pronunUsMan = pronunUsMan;
	}

	public Integer getServerId() {
		return this.serverId;
	}

	public void setServerId(Integer serverId) {
		this.serverId = serverId;
	}

	public Integer getWordRootId() {
		return this.wordRootId;
	}

	public void setWordRootId(Integer wordRootId) {
		this.wordRootId = wordRootId;
	}

	public Integer getBookId() {
		return this.bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	public Integer getCharacterId() {
		return this.characterId;
	}

	public void setCharacterId(Integer characterId) {
		this.characterId = characterId;
	}

	public Integer getPageNo() {
		return this.pageNo;
	}

	public void setPageNo(Integer pageNo) {
		this.pageNo = pageNo;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Integer getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(Integer updateBy) {
		this.updateBy = updateBy;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Integer getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(Integer delFlag) {
		this.delFlag = delFlag;
	}

}
