package cn.xdf.learn.entity;

// Generated 2015-5-14 10:00:42 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * WdWordDef generated by hbm2java
 */
public class WdWordDef implements java.io.Serializable {

	private Integer id;
	private Integer wordId;
	private String wordProp;
	private String definition;
	private String defTag;
	private Integer orderNum;
	private String remarks;
	private Integer createBy;
	private Date createTime;
	private Integer updateBy;
	private Date updateTime;
	private Integer delFlag;

	public WdWordDef() {
	}

	public WdWordDef(Integer wordId, String wordProp, String definition,
			String defTag, Integer orderNum, String remarks, Integer createBy,
			Date createTime, Integer updateBy, Date updateTime, Integer delFlag) {
		this.wordId = wordId;
		this.wordProp = wordProp;
		this.definition = definition;
		this.defTag = defTag;
		this.orderNum = orderNum;
		this.remarks = remarks;
		this.createBy = createBy;
		this.createTime = createTime;
		this.updateBy = updateBy;
		this.updateTime = updateTime;
		this.delFlag = delFlag;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getWordId() {
		return this.wordId;
	}

	public void setWordId(Integer wordId) {
		this.wordId = wordId;
	}

	public String getWordProp() {
		return this.wordProp;
	}

	public void setWordProp(String wordProp) {
		this.wordProp = wordProp;
	}

	public String getDefinition() {
		return this.definition;
	}

	public void setDefinition(String definition) {
		this.definition = definition;
	}

	public String getDefTag() {
		return this.defTag;
	}

	public void setDefTag(String defTag) {
		this.defTag = defTag;
	}

	public Integer getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(Integer updateBy) {
		this.updateBy = updateBy;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(Integer delFlag) {
		this.delFlag = delFlag;
	}

}
